### ISSUE TITLE
Add support for zst compression when unstripping

### ISSUE THREAD

**Issue by Myldero** [io12/pwninit#278]
In some versions of ubuntu libc debug symbols, data.tar has the extension zst, which isn't supported currently, so unstripping fails. Example: [https://launchpad.net/ubuntu/+archive/primary/+files/libc6-dbg_2.34-0ubuntu1_amd64.deb](https://launchpad.net/ubuntu/+archive/primary/+files/libc6-dbg_2.34-0ubuntu1_amd64.deb)

**Comment by io12** [comment]
Should be fixed in 3.2.0. Thanks!
