### ISSUE TITLE
error: failed to run custom build command for `rust-lzma v0.4.0`

### ISSUE THREAD

**Issue by Arinerron** [io12/pwninit#6]
I'm trying to install pwninit on a Debian box on AWS but am getting this error:

```
error: failed to run custom build command for `rust-lzma v0.4.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installP91vdS/release/build/rust-lzma-879711f934ca58da/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Could not find liblzma using pkg-config', /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-lzma-0.4.0/build.rs:10:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `pwninit v2.1.0`, intermediate artifacts can be found at `/tmp/cargo-installP91vdS`

Caused by:
  build failed
```

I don't do anything rust related and I have never used cargo. Could you point me in the right direction?

**Comment by io12** [comment]
You have to install `liblzma-dev`.

**Comment by Arinerron** [comment]
Thank you for the prompt reply! That makes sense and I did install the package, but I'm still getting the error. 

fyi: I set the env var it tells you to for the backtrace but the output didn't change.

**Comment by io12** [comment]
Does `pkg-config --libs liblzma` show anything? Actually the problem might be that you don't have `pkg-config`.

**Comment by Arinerron** [comment]
Yup that was it, tyvm.
