### ISSUE TITLE
Integrate patchelf

### ISSUE THREAD

**Issue by fuyu0425** [io12/pwninit#85]
Hello,
I recently found this package randomly from AUR. Great Work!
This tool is very useful and automates what I do manually, especially the unstrip libc part.

Do you consider integrating things like `patchelf`?
Although `pwntools` can works fine, if we can use `patchelf` to set `rpath` and `interpreter`, we can even debug it naturally in gdb!

The following is the snippet I do manually everytime.
```
patchelf --set-interpreter ./ld-2.27.so ./target
patchelf --set-rpath `pwd` ./target # for libc.so.6
```

Thanks for such a great tool again!

**Comment by io12** [comment]
Glad you like the tool! I thought about integrating `patchelf` a bit in https://github.com/io12/pwninit/issues/15, but I haven't really worked on `pwninit` recently. I guess integrating `patchelf` shouldn't be too hard though.
