### ISSUE TITLE
Patching rpath fails for 

### ISSUE THREAD

**Issue by maybe-sybr** [io12/pwninit#87]
Hey @io12 . I've just grabbed the 3.0 release and noticed that the `patchelf` step attempts to set the `rpath` to an empty string if a pathless filename is used for the libc arg, e.g. `--libc my_libc.so`. That's because `libc.parent() -> ""` here:
https://github.com/io12/pwninit/blob/4821f6495b52a5c04f38d983f7ded4ca1f696395/src/patch_bin.rs#L54

having this default to `"."` would be helpful, I'm just working around it by specifying `--libc ./my_libc.so` which seems to work fine. It might also be better to absolutify that path so running the binary works from other directories though - equivalent to running `--libc "${PWD}/my_libc.so"`.

Thanks for the tool, btw!

**Comment by io12** [comment]
Should be fixed now, thanks! I'll bump the release now.
